### ISSUE TITLE
FAQ Functionality breaks after searching.

### ISSUE THREAD

**Issue by DeveloperTommy** [ArtRank/ArtRank#42]
After attempting to use the search bar to search for any query, pressing FAQ does not take the user to the FAQ page. For example, if I search for “cars”, this leads to my search results page. Once on the search results, if I click on FAQ, I am not directed to the FAQ page. Instead I remain on the same page where the page displays:

![bug1](https://cloud.githubusercontent.com/assets/6621667/7148796/699c7b68-e2d4-11e4-92d9-69399ca23517.png)

**Comment by patbeagan1** [comment]
As of right now, the functionality only works for predefined tags like "nature". We'll work on expanding it
