### ISSUE TITLE
Experiencing Downtime on the Application for Periods of Time

### ISSUE THREAD

**Issue by DeveloperTommy** [ArtRank/ArtRank#43]
Specifically after visiting the home page, clicking "Vote on this Matchingup" in the sidebar on the left generates this image: 

![bug2](https://cloud.githubusercontent.com/assets/6621667/7148953/ef4358d0-e2d5-11e4-89a3-4fe90ea81b0a.png)

**Comment by NateFuller** [comment]
+1 We are unable to properly test the release because of this. We will be testing the local version instead.

**Comment by Setsun** [comment]
Checkout forever-monitor.js for how to restart the server upon app crash.
