### ISSUE TITLE
"Choose File" button not working properly upon cancellation

### ISSUE THREAD

**Issue by NateFuller** [ArtRank/ArtRank#44]
#### Description
The "Choose File" button on the upload page does not seem to be working correctly. If I add an image, but then go back in and cancel it doesn't preserve the original image I've chosen.

#### Steps to reproduce
- Navigate to upload page
- Fill in 'Title', 'Artist', and 'Tags' fields
- Click "Choose File"
- Choose a file. At this point, the text next to the "Choose File" button should be the filename that you chose.
- Click "Choose FIle" again.
- Click "Cancel" from the resulting pop-up window in order to cancel image selection (or press the Esc key)
- The text next to the "Choose File" button now says "No file chosen"

#### Expected behavior
- The text next to the "Choose File" button should remain equal to the last image that was chosen

#### Screens
![screen shot 2015-04-14 at 7 02 30 pm](https://cloud.githubusercontent.com/assets/4147804/7149260/3c2ffaf6-e2d9-11e4-84b0-0927683eb85b.png)
------------------------------
![screen shot 2015-04-14 at 7 02 51 pm](https://cloud.githubusercontent.com/assets/4147804/7149262/47c49cd2-e2d9-11e4-89c1-b15147e01ef3.png)
------------------------------
![screen shot 2015-04-14 at 7 03 26 pm](https://cloud.githubusercontent.com/assets/4147804/7149266/4a62563c-e2d9-11e4-9ff1-d2a131d9d451.png)
------------------------------

**Comment by AdonisFamilia** [comment]
This is expected behavior not a bug
