### ISSUE TITLE
Flash of Raw Information before styles are applied when loading page

### ISSUE THREAD

**Issue by ssd12** [ArtRank/ArtRank#45]
#### Steps to reproduce:
- Navigate to homepage
- Observe brief flash of raw data as page loads

**Comment by NateFuller** [comment]
#### Screenshot of the issue
![screen shot 2015-04-14 at 7 17 29 pm](https://cloud.githubusercontent.com/assets/4147804/7149417/2be31532-e2db-11e4-8048-9aebb45bc9e8.png)

**Comment by Michael-McCarthy** [comment]
Fixed in commit fc6608020dc3a4af4310d295d45695b4f9e058c8.
