### ISSUE TITLE
Unable to recognize which images are magnifiable

### ISSUE THREAD

**Issue by ssd12** [ArtRank/ArtRank#47]
#### Description 

Unable to identify which images can be magnified. For example, on the homepage under "Highest Ranked Art", when hovering over an image- a pointer cursor doesn't show up. This makes it unclear as to whether image is magnifiable. 

#### Suggestions

When hovering over an image- cursor should change to style in order for user to discern whether it can be magnified or not. Another suggestion is that when hovering over an image, it's thumbnail get darker, or text may appear over it, i.e. "Click to Enlarge".

**Comment by patbeagan1** [comment]
Use css cursor, to see if it is magnifiable

**Comment by Setsun** [comment]
Check out CSS property, cursor for potential fix.

**Comment by patbeagan1** [comment]
cursor is in place
